
# Generated by Django 4.0.5 on 2022-06-07 10:17


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=64, verbose_name='아이디')),
                ('pw', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('zipcode', models.CharField(max_length=64, verbose_name='우편번호')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('address', models.CharField(max_length=64, verbose_name='주소')),
                ('address_detail', models.CharField(max_length=64, verbose_name='상세주소')),
                ('picture', models.CharField(max_length=100, verbose_name='사진파일이름')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원 리스트',
                'db_table': 'yummy_member',
            },
        ),
    ]
