# Generated by Django 4.0.5 on 2022-06-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=64, verbose_name='작성자')),
                ('content', models.CharField(max_length=1000, verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
            ],
            options={
                'verbose_name': '리뷰 게시판_댓글',
                'verbose_name_plural': '리뷰 게시판_댓글',
                'db_table': 'yummy_board_reply',
            },
        ),
    ]
