# Generated by Django 4.0.5 on 2022-06-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('content', models.TextField(max_length=64, verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('update_date', models.DateTimeField(verbose_name='수정일자')),
                ('delete_date', models.DateTimeField(verbose_name='삭제일자')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '리뷰 게시판',
                'verbose_name_plural': '리뷰 게시판',
                'db_table': 'yummy_board',
            },
        ),
    ]
